[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "alexstevovich-kebab-to-snake"
version = "1.0.0"
description = "Convert hyphens in a string to underscores"
requires-python = ">=3.11"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
